Repository unc-csxl/csxl.unc.edu, pull requests merged in 2023-10, with the labels that each got.

#107 Implement the Events Feature Backend
  backend/api/events.py
  backend/api/organizations.py
  backend/entities/__init__.py
  backend/entities/event_entity.py
  backend/entities/organization_entity.py
  backend/main.py
  backend/models/__init__.py
  backend/models/event.py
  backend/models/event_details.py
  backend/models/organization_details.py
  backend/script/demo_reset.py
  backend/script/test_reset.py
  backend/services/event.py
  backend/services/organization.py
  backend/test/services/event/__init__.py
  backend/test/services/event/event_demo_data.py
  backend/test/services/event/event_test_data.py
  backend/test/services/organization/organization_demo_data.py
Labels: enhancement

#108 Implement the Frontend for the Events Feature
  backend/entities/event_entity.py
  backend/test/services/event/event_demo_data.py
  backend/test/services/event/event_test_data.py
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/event/event-details/event-details.component.css
  frontend/src/app/event/event-details/event-details.component.html
  frontend/src/app/event/event-details/event-details.component.ts
  frontend/src/app/event/event-filter/event-filter.pipe.ts
  frontend/src/app/event/event-page/event-page.component.css
  frontend/src/app/event/event-page/event-page.component.html
  frontend/src/app/event/event-page/event-page.component.ts
  frontend/src/app/event/event-routing.module.ts
  frontend/src/app/event/event.module.ts
  frontend/src/app/event/event.resolver.ts
  frontend/src/app/event/event.service.ts
  frontend/src/app/event/widgets/event-card/event-card.widget.css
  frontend/src/app/event/widgets/event-card/event-card.widget.html
  frontend/src/app/event/widgets/event-card/event-card.widget.ts
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.css
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.html
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.ts
  frontend/src/app/navigation/navigation.component.html
  frontend/src/app/shared/search-bar/search-bar.widget.html
Labels: enhancement

#112 Events Feature Refactor - Documentation
  backend/entities/event_entity.py
  backend/entities/organization_entity.py
  backend/entities/permission_entity.py
  backend/entities/role_entity.py
  backend/entities/user_entity.py
  backend/entities/user_role_table.py
  backend/models/event.py
  backend/models/event_details.py
  backend/models/organization.py
  backend/models/organization_details.py
  backend/models/pagination.py
  backend/models/permission.py
  backend/models/role.py
  backend/models/role_details.py
  backend/models/unregistered_user.py
  backend/models/user.py
  backend/models/user_details.py
  backend/script/delete_database.py
  backend/script/reset_demo.py
  backend/script/reset_testing.py
  backend/services/event.py
  backend/services/exceptions.py
  backend/services/github.py
  backend/services/health.py
  backend/services/organization.py
  backend/services/permission.py
  backend/services/role.py
  backend/services/user.py
  frontend/src/app/admin/organization/admin-organization.service.ts
  frontend/src/app/admin/organization/list/admin-organization-list.component.ts
  frontend/src/app/event/event-details/event-details.component.ts
  frontend/src/app/event/event-filter/event-filter.pipe.ts
  frontend/src/app/event/event-page/event-page.component.html
  frontend/src/app/event/event-page/event-page.component.ts
  frontend/src/app/event/event-routing.module.ts
  frontend/src/app/event/event.model.ts
  frontend/src/app/event/event.module.ts
  frontend/src/app/event/event.resolver.ts
  frontend/src/app/event/event.service.ts
  frontend/src/app/event/widgets/event-card/event-card.widget.css
  frontend/src/app/event/widgets/event-card/event-card.widget.html
  frontend/src/app/event/widgets/event-card/event-card.widget.ts
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.html
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.ts
  frontend/src/app/organization/organization-details/organization-details.component.ts
  frontend/src/app/organization/organization-editor/organization-editor.component.ts
  frontend/src/app/organization/organization-filter/organization-filter.pipe.ts
  frontend/src/app/organization/organization-page/organization-page.component.ts
  frontend/src/app/organization/organization-routing.module.ts
  frontend/src/app/organization/organization.model.ts
  frontend/src/app/organization/organization.module.ts
  frontend/src/app/organization/organization.resolver.ts
  frontend/src/app/organization/organization.service.ts
  frontend/src/app/organization/rx-organization.ts
  frontend/src/app/organization/widgets/organization-card/organization-card.widget.ts
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.ts
Labels: documentation

#116 Event Management Functionality
  backend/api/organizations.py
  backend/entities/organization_entity.py
  backend/services/event.py
  backend/services/organization.py
  backend/test/services/event/event_test.py
  frontend/src/app/app.module.ts
  frontend/src/app/event/event-details/event-details.component.html
  frontend/src/app/event/event-editor/event-editor.component.css
  frontend/src/app/event/event-editor/event-editor.component.html
  frontend/src/app/event/event-editor/event-editor.component.ts
  frontend/src/app/event/event-filter/event-filter.pipe.ts
  frontend/src/app/event/event-page/event-page.component.html
  frontend/src/app/event/event-page/event-page.component.ts
  frontend/src/app/event/event-routing.module.ts
  frontend/src/app/event/event.model.ts
  frontend/src/app/event/event.module.ts
  frontend/src/app/event/event.resolver.ts
  frontend/src/app/event/event.service.ts
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.css
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.html
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.ts
  frontend/src/app/organization/organization-details/organization-details.component.css
  frontend/src/app/organization/organization-details/organization-details.component.html
  frontend/src/app/organization/organization-details/organization-details.component.ts
  frontend/src/app/organization/organization.model.ts
  frontend/src/app/organization/organization.module.ts
  frontend/src/app/organization/organization.resolver.ts
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.css
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html
  frontend/src/app/shared/event-card/event-card.widget.css
  frontend/src/app/shared/event-card/event-card.widget.html
  frontend/src/app/shared/event-card/event-card.widget.ts
  frontend/src/app/shared/event-list/event-list.widget.css
  frontend/src/app/shared/event-list/event-list.widget.html
  frontend/src/app/shared/event-list/event-list.widget.ts
  frontend/src/app/shared/shared.module.ts
Labels: enhancement

#120 Fix Frontend Visual Bugs in Production
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.css
  frontend/src/app/shared/event-list/event-list.widget.html
Labels: bug

#121 Fix Sorting Bug for Events Page
  frontend/src/app/event/event-filter/event-filter.pipe.ts
  frontend/src/app/event/event.model.ts
  frontend/src/app/event/event.service.ts
Labels: bug

#123 Fix Organization Detail Page Crash
  frontend/src/app/event/event.model.ts
  frontend/src/app/event/event.service.ts
Labels: bug

#125 Port Organization Details Crash Fix
  backend/api/events.py
  backend/services/event.py
  backend/test/services/event/event_test.py
  frontend/src/app/event/event.service.ts
  frontend/src/app/organization/organization-details/organization-details.component.ts
  frontend/src/app/organization/organization.resolver.ts
Labels: bug

#128 Migrate CSXL Application to Cohesive Design
  frontend/src/app/about/about.component.html
  frontend/src/app/admin/roles/details/admin-role-details.component.html
  frontend/src/app/admin/roles/list/admin-roles-list.component.html
  frontend/src/app/coworking/ambassador-home/ambassador-home.component.html
  frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html
  frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.html
  frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html
  frontend/src/app/event/event-editor/event-editor.component.css
  frontend/src/app/event/event-editor/event-editor.component.html
  frontend/src/app/organization/organization-editor/organization-editor.component.css
  frontend/src/app/organization/organization-editor/organization-editor.component.html
  frontend/src/app/organization/widgets/organization-card/organization-card.widget.html
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html
  frontend/src/app/profile/profile-editor/profile-editor.component.css
  frontend/src/app/profile/profile-editor/profile-editor.component.html
  frontend/src/styles.scss
Labels: enhancement

#129 Add Right Padding to Org Details Event List
  frontend/src/app/organization/organization-details/organization-details.component.css
Labels: bug
