Repository unc-csxl/csxl.unc.edu, pull requests merged in 2023-11, with the labels that each got.

#149 Feature Permissions Document
  docs/admin_permissions.md
  docs/auth.md
Labels: documentation

#150 Resolve Date Time Issues
  frontend/src/app/event/event-editor/event-editor.component.html
  frontend/src/app/event/event-editor/event-editor.component.ts
  frontend/src/app/event/event-filter/event-filter.pipe.ts
Labels: bug

#151 Improve UX When Navigating to an Invalid Organization
  frontend/src/app/organization/organization-details/organization-details.component.html
  frontend/src/app/organization/organization-details/organization-details.component.ts
  frontend/src/app/organization/organization.module.ts
  frontend/src/app/organization/organization.resolver.ts
  frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.css
  frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.html
  frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.ts
Labels: enhancement

#155 Pass Initial Selected Event Through Pipe
  frontend/src/app/event/event-page/event-page.component.ts
Labels: bug

#157 Fix Organization Permissions
  backend/api/organizations.py
  backend/services/exceptions.py
  backend/services/organization.py
  backend/test/services/organization/organization_test.py
  docs/admin_permissions.md
  frontend/src/app/about/about.component.html
  frontend/src/app/admin/organization/list/admin-organization-list.component.ts
  frontend/src/app/admin/roles/details/admin-role-details.component.html
  frontend/src/app/admin/roles/list/admin-roles-list.component.html
  frontend/src/app/coworking/ambassador-home/ambassador-home.component.html
  frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html
  frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.html
  frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html
  frontend/src/app/event/event-editor/event-editor.component.html
  frontend/src/app/event/event-editor/event-editor.component.ts
  frontend/src/app/event/event-filter/event-filter.pipe.ts
  frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.ts
  frontend/src/app/organization/organization-details/organization-details.component.html
  frontend/src/app/organization/organization-details/organization-details.component.ts
  frontend/src/app/organization/organization-editor/organization-editor.component.html
  frontend/src/app/organization/organization-editor/organization-editor.component.ts
  frontend/src/app/organization/organization.module.ts
  frontend/src/app/organization/organization.resolver.ts
  frontend/src/app/organization/widgets/organization-card/organization-card.widget.html
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html
  frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.ts
  frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.html
  frontend/src/app/profile/profile-editor/profile-editor.component.html
Labels: bug

#164 Protect EventRegistrations attendees from accidental API disclosure
  backend/api/events.py
  backend/entities/event_entity.py
  backend/entities/event_registration_entity.py
  backend/models/event_details.py
  backend/models/event_registration.py
  backend/services/event.py
  backend/test/services/event/event_test.py
  backend/test/services/event/event_test_data.py
Labels: DONT MERGE

#165 Create Documentation for SQLAlchemy Database Relationships for COMP 423
  docs/images/sqlalchemy/association.png
  docs/images/sqlalchemy/circularity.png
  docs/images/sqlalchemy/many_one.png
  docs/images/sqlalchemy/many_two.png
  docs/images/sqlalchemy/no_circularity.png
  docs/images/sqlalchemy/one-to-many.png
  docs/images/sqlalchemy/one-to-one.png
  docs/sqlalchemy/relationships.md
Labels: documentation

#173 Create More Documentation for SQLAlchemy for COMP 423
  docs/images/sqlalchemy/entities.png
  docs/images/sqlalchemy/entities_only.png
  docs/images/sqlalchemy/tech-stack-db.png
  docs/images/sqlalchemy/tech-stack-no-db.png
  docs/images/sqlalchemy/tech-stack-with-alchemy.png
  docs/sqlalchemy/0_introduction.md
  docs/sqlalchemy/1_sqlalchemy_core_and_orm.md
  docs/sqlalchemy/2_entities.md
  docs/sqlalchemy/3_connecting_to_database.md
  docs/sqlalchemy/4_crud_operations.md
  docs/sqlalchemy/5_relationships.md
Labels: documentation

#174 Fix Issues in SQLAlchemy Docs
  docs/sqlalchemy/0_introduction.md
  docs/sqlalchemy/1_sqlalchemy_core_and_orm.md
  docs/sqlalchemy/2_entities.md
Labels: documentation

#175 Fix Image Links in SQLAlchemy Docs
  docs/sqlalchemy/0_introduction.md
  docs/sqlalchemy/1_sqlalchemy_core_and_orm.md
  docs/sqlalchemy/2_entities.md
  docs/sqlalchemy/4_crud_operations.md
Labels: documentation

#176 Add Important Point to Entities Docs
  docs/sqlalchemy/2_entities.md
Labels: documentation

#179 Create Documentation about Middleware Error Handling for COMP 423
  docs/backend/middleware.md
  docs/images/backend/middleware.jpeg
  docs/images/backend/no_middleware.jpeg
Labels: documentation
