Repository unc-csxl/csxl.unc.edu, pull requests merged in 2025-01, with the labels that each got.

#666 Add Instructions to Import Roster Dialog
  frontend/package-lock.json
  frontend/src/app/my-courses/course/roster/roster.component.ts
  frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.css
  frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.html
Labels: design

#667 Roster Import Description Patch
  frontend/src/app/my-courses/course/roster/roster.component.ts
  frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.html
  frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.ts
Labels: bug

#631 [Exploration] Office Hours Querying Enhancements
  backend/services/academics/course_site.py
  backend/services/office_hours/office_hours.py
  backend/test/services/academics/term_data.py
  frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.css
  frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.ts
Labels: exploration, refactor

#652 Task/CSXL-597: Recurring Office Hours Events
  backend/api/office_hours/office_hours.py
  backend/entities/office_hours/__init__.py
  backend/entities/office_hours/office_hours_entity.py
  backend/entities/office_hours/office_hours_recurrence_pattern_entity.py
  backend/main.py
  backend/migrations/versions/41c5d192f495_migration_for_task_csxl_597.py
  backend/models/academics/my_courses.py
  backend/models/office_hours/office_hours.py
  backend/models/office_hours/office_hours_details.py
  backend/models/office_hours/office_hours_recurrence_pattern.py
  backend/services/academics/course_site.py
  backend/services/exceptions.py
  backend/services/office_hours/__init__.py
  backend/services/office_hours/office_hours.py
  backend/services/office_hours/office_hours_recurrence.py
  backend/test/services/academics/course_site_test.py
  backend/test/services/office_hours/fixtures.py
  backend/test/services/office_hours/office_hours_data.py
  backend/test/services/office_hours/office_hours_recurrence_test.py
  frontend/src/app/my-courses/course/course.component.ts
  frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.css
  frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.html
  frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.ts
  frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.ts
  frontend/src/app/my-courses/course/office-hours/office-hours.resolver.ts
  frontend/src/app/my-courses/dialogs/delete-recurring-event/delete-recurring-event.dialog.css
  frontend/src/app/my-courses/dialogs/delete-recurring-event/delete-recurring-event.dialog.html
  frontend/src/app/my-courses/dialogs/delete-recurring-event/delete-recurring-event.dialog.ts
  frontend/src/app/my-courses/my-courses.model.ts
  frontend/src/app/my-courses/my-courses.module.ts
  frontend/src/app/my-courses/my-courses.service.ts
Labels: feature, REQUIRES MIGRATION
